### ISSUE TITLE
Wrong description in read

### ISSUE THREAD

**Issue by sdd330** [crazycodeboy/react-native-awesome#5]
The following section:
## 一次学习，随处可写
- [react-native-macos](https://github.com/ptmt/react-native-macos)：使用React Native组建Web应用。
- [react-native-web](https://github.com/necolas/react-native-web)：使用React Native和Cocoa组建macOS桌面应用。

Should be updated to:
- [react-native-macos](https://github.com/ptmt/react-native-macos)：使用React Native和Cocoa组建macOS桌面应用。
- [react-native-web](https://github.com/necolas/react-native-web)：使用React Native组建Web应用。

**Comment by crazycodeboy** [comment]
thanks
